import NavBar from "@/components/header/NavBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Full Stack Task App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavBar />
      {children}
    </div>
  );
}
